### ISSUE TITLE
apt installation errors, dependency errors

### ISSUE THREAD

**Issue by henild** [s-h-3-l-l/katoolin3#8] opened 2019-09-29 16:20 UTC
Are the server down or there is a problem with my installation?

**Comment by s-h-3-l-l** [comment] 2019-09-29 16:55
According to [stackexchange](https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure) this may be a firewall issue.

Try this and tell if me if it works:
```
sudo apt-key adv -qq --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys ED444FF07D8D0BF6
```

**Comment by s-h-3-l-l** [comment] 2019-09-29 20:43
test

**Comment by s-h-3-l-l** [comment] 2019-09-29 21:36
tsetset

**Comment by s-h-3-l-l** [comment] 2019-09-29 21:52
test...

**Comment by s-h-3-l-l** [comment] 2019-09-29 21:53
test2...

**Comment by henild** [comment] 2019-09-30 06:20
Yeah, it did but not by just running the command you provided but changing that bit in the install.sh script. So it would be great if you could just update the install.sh file.
Thanks.

**Comment by henild** [comment] 2019-09-30 07:20
Also after installing Katoolin3 "Get:18 http://ftp.harukasan.org/kali kali-rolling/main amd64 Packages [16.6 MB]" this line get added whenever I try to update apt-get. Is it normal and will this process do every time I update apt-get? Is there a way to remove it after installing katoolin. My internet speed is quite good but still, it takes every time around 10 min to fetch all data from it(there server issues maybe).

**Comment by s-h-3-l-l** [comment] 2019-09-30 11:09
I added the new line to ```install.sh```.
This was fixed in commit cd0da5d146ac7ae7277804dbee9bfa91faa85aa4.

The line with http://ftp.harukasan.org/kali you get should definitely NOT be there outside of katoolin3. This is only normal when katoolin3 is still running. 
If you already quit katoolin3 try removing the file ```/etc/apt/sources.list.d/katoolin3.list``` and then execute ```apt-get update``` again.

**Comment by henild** [comment] 2019-09-30 11:55
Ok so I completely removed katoolin from my system cloned it again did the installation and updated again to ensure it. And the ftp problem is solved. But whenever I run katoolin that FTP thing take 10-15 minute to load and also I tried installing the tools it shows cannot install "package name" for some programs and then show installing 309 packages and take forever. Is this a server problem?
EDIT : Here is the link to error https://pastebin.com/he8f3wCi
EDIT2 : After waiting for more time its ignoring every package

**Comment by s-h-3-l-l** [comment] 2019-09-30 13:35
That the FTP server takes so long is because it's very unstable so there is no way (to my knowledge) to shorten this waiting time programmatically.

The errors you get are caused by apt-get internally (probably some dependency errors).
To recover those packages you can try:
```
sudo apt-get clean;
sudo dpkg --configure -a;
```

After katoolin3 shows "installing 309 packages" it downloads all those packages from the repository that's why it takes so long. I will add a progress bar there.

**Comment by henild** [comment] 2019-09-30 17:27
I don't know why all this has not been working for me I was not able to install packages and I don't know how but that FTP thing again showed up in the apt-get update after it was fixed. I was not able to wait 15 min every time I try to run katoolin from terminal. I will be waiting for a stable release or can you suggest me an alternative way to install all kali linux softwares?

**Comment by s-h-3-l-l** [comment] 2019-09-30 18:25
Sorry that you can't get it running.

Maybe try [the old katoolin](https://github.com/LionSec/katoolin) or install some tools individually from [tools.kali.org](https://tools.kali.org/tools-listing).

**Closed as completed** 2019-09-30 18:27 UTC
Labels: unfixed :(
